# Changes here will be overwritten by Copier
_commit: v2.0.7
_src_path: gh:lincc-frameworks/python-project-template
author_email: axel.guinot.astro@gmail.com
author_name: Axel Guinot
create_example_module: false
custom_install: true
enforce_style:
- ruff_lint
- ruff_format
failure_notification:
- email
include_benchmarks: false
include_docs: true
include_notebooks: false
mypy_type_checking: none
package_name: roman_shear_sims
project_license: MIT
project_name: roman-shear-sims
project_organization: None
python_versions:
- '3.9'
- '3.10'
- '3.11'
- '3.12'
- '3.13'
test_lowest_version: direct
